CREATE TABLE Projects (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT,
	category TEXT,
	funding_goal INTEGER,
	start_date TEXT,
	end_date TEXT
);

CREATE TABLE Pledges (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	amount INTEGER,
	user_id INTEGER,
	project_id INTEGER
);

CREATE TABLE Users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT,
	age INTEGER
);
